spring:
  application:
    name: eureka-service

# =======================================
# --- local 프로필 활성화 시 사용될 설정 ---
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# =======================================
# --- docker 프로필 활성화 시 사용될 설정 ---
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-service
  client:
    register-with-eureka: false
    fetch-registry: false